tasks:
  - before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install faas-cli pre-commit

      pre-commit install --install-hooks

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
