image: gitpod/workspace-mongodb

ports:
  - name: MongoDB
    port: 27017
    onOpen: notify

  - name: Mongoose CRUD
    port: 3000
    onOpen: notify

  - name: Golang CRUD
    port: 3001
    onOpen: notify

tasks:
  - name: MongoDB
    command: mongod

  - name: Setup
    before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install faas-cli pre-commit

      pre-commit install --install-hooks

      exit 0

  - name: Mongoose CRUD
    env:
      APP_URL: http://localhost:3000
      http_port: "3000"
      MONGODB_URL: mongodb://localhost:27017/mongoose-crud
    init: |
      cd ${GITPOD_REPO_ROOT}/template/mongoose-crud
      npm ci
    command: |
      cd ${GITPOD_REPO_ROOT}/template/mongoose-crud
      npm run start:dev

  - name: Golang CRUD
    env:
      http_port: "3001"
      MONGODB_URL: mongodb://localhost:27017
    init: |
      cd ${GITPOD_REPO_ROOT}/template/golang-crud
      go install

      go install github.com/cosmtrek/air@latest
    command: |
      cd ${GITPOD_REPO_ROOT}/template/golang-crud

      air

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - ms-vscode.vscode-typescript-next
    - golang.go
    - mongodb.mongodb-vscode
