name: Golang CRUD
on:
  pull_request:
    paths:
      - templates/golang-crud/**
      - .github/workflows/golang-crud.yml
  push:
    paths:
      - templates/golang-crud/**
      - .github/workflows/golang-crud.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./template/golang-crud

      - name: go-fmt-import
        uses: Jerome1337/goimports-action@v1.0.2
        with:
          goimports-path: ./template/golang-crud

      - name: go-vet
        working-directory: ./template/golang-crud
        run: go vet -v ./...

      - name: gofumpt
        working-directory: ./template/golang-crud
        run: |
          go install mvdan.cc/gofumpt@latest

          LIST_OF_FILES=$(gofumpt -l .)
          echo "$LIST_OF_FILES"
          if [ -n "$LIST_OF_FILES" ];then
              exit 1
          fi

      - name: go-err-check
        working-directory: ./template/golang-crud
        run: |
          go install github.com/kisielk/errcheck@latest

          errcheck ./...

      - name: go-static-check
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
          working-directory: ./template/golang-crud
