name: Mongoose CRUD
on:
  pull_request:
    paths:
      - templates/mongoose-crud/**
      - .github/workflows/mongoose-crud.yml
  push:
    paths:
      - templates/mongoose-crud/**
      - .github/workflows/mongoose-crud.yml
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node:
          - 14
          - 16
          - 18
        mongodb:
          - 3.6
          - 4
          - 5
          - 6
          - latest
    services:
      mongo:
        image: mongo:${{ matrix.mongodb }}
        ports:
          - 27017:27017
    env:
      APP_URL: http://0.0.0.0:3000
      MONGODB_URL: mongodb://0.0.0.0:27017/crud
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        working-directory: template/mongoose-crud
        run: |
          npm ci
          cd function
          npm ci

      - name: Lint
        working-directory: template/mongoose-crud
        run: |
          npm run lint

      - name: Start application
        working-directory: template/mongoose-crud
        run: npm run start:dev &

      - name: Run e2e tests
        working-directory: template/mongoose-crud
        run: npm run test:e2e
